### ISSUE TITLE
xud-simnet-upgrade script

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud-simnet#10]
Following

> cd ~/xud-simnet
> git fetch
> git pull
> source setup.bash
> xud-simnet-stop
> xud-simnet-clean
> xud-simnet-install
> xud-simnet-start

lndbtc was not syncing (stuck at previous block height). `rm -rf`, `git clone` and new `xud-simnet-install` solved it.

**Comment by kilrau** [comment]
this issue is about our official "instructions" on how to upgrade

**Comment by offerm** [comment]
@kilrau 
I'm not sure about the need for an update script.

For now, I suggest to include a check in xud-simnet-start if xud is updated to the master branch and if not automatically pull and compile it before starting XUD.

All the other tools should be stable.

OK?

**Comment by kilrau** [comment]
Sounds good!

**Comment by offerm** [comment]
Done
