### ISSUE TITLE
raiden didn't start properly

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud-simnet#30]
```
~/xud-simnet$ xud-simnet-start
starting all processes
btcd started
ltcd started
lndbtc started
lndltc started
raiden didn't start properly
```

[raiden-debug_2019-06-10T17:27:23.310694.log](https://github.com/ExchangeUnion/xud-simnet/files/3273114/raiden-debug_2019-06-10T17.27.23.310694.log)
[raiden-debug_2019-06-10T17:31:54.993663.log](https://github.com/ExchangeUnion/xud-simnet/files/3273115/raiden-debug_2019-06-10T17.31.54.993663.log)

**Comment by erkarl** [comment]
Can you check the output of `/tmp/raiden.log`?

**Comment by kilrau** [comment]
Not much..
[raiden.log](https://github.com/ExchangeUnion/xud-simnet/files/3273522/raiden.log)

**Comment by kilrau** [comment]
`~/xud-simnet/raiden-wd$ ps aux | grep raiden
kilrau   12097  0.0  0.0  21536  1096 pts/0    S+   21:44   0:00 grep --color=auto raiden
root     15182  0.2  0.1 350200 20840 ?        Sl   19:10   0:25 /opt/venv/bin/python3 -m raiden --address 0x4ecdfBF7263A84d3567C2559644Ae5BbB20A4bee --keystore-path /root/.ethereum/testnet/keystore --accept-disclaimer --eth-rpc-endpoint http://geth:8545 --network-id ropsten --password-file /root/.ethereum/passphrase.txt`

**Comment by kilrau** [comment]
Solved, there were 2 raiden instaces running and one took port 5001 so the other couldn't start properly
