### ISSUE TITLE
Change simnet node records + gcloud naming

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud-simnet#36]
TODO:

- [ ] @kilrau Change aname records to
```
xud1.simnet.exchangeunion.com
xud2.simnet.exchangeunion.com
xud3.simnet.exchangeunion.com
```
- [x] @offerm restart xud1,2,3 - and rename the instances on google cloud to the same
```
xud1-simnet-exchangeunion-com
xud2-simnet-exchangeunion-com
xud3-simnet-exchangeunion-com
```
- [ ] @offerm change hardcoded xud simnet bootstrap nodes to the same

**Comment by offerm** [comment]
@kilrau Not sure what you want me to do on GC. Should I just rename the instances?

https://stackoverflow.com/questions/27940480/rename-google-compute-engine-vm-instance

Rename should be done by recreate. Please confirm.

About the A records - please go ahead and add these A records (don't yet touch the old ones). Let me know once you are done.

**Comment by kilrau** [comment]
> @kilrau Not sure what you want me to do on GC. Should I just rename the instances?
> https://stackoverflow.com/questions/27940480/rename-google-compute-engine-vm-instance
> Rename should be done by recreate. Please confirm.

I renamed another instance by: shutting down, click on it, edit, rename, boot up. No problems. Let's not make it too complicated.

> About the A records - please go ahead and add these A records (don't yet touch the old ones). Let me know once you are done.

Done.
```
A | xud1.simnet | points to 35.196.118.79
A | xud2.simnet | points to 35.231.171.148
A | xud3.simnet | points to 35.229.81.83
```

**Comment by offerm** [comment]
@kilrau  Can you please remove the old A record for test2?

Will make some tests

**Comment by offerm** [comment]
@kilrau 
xud-simnet looks clean. 

However

XUD code has this:
```
export default [
  {
    nodePubKey: '02b66438730d1fcdf4a4ae5d3d73e847a272f160fee2938e132b52cab0a0d9cfc6',
    addresses: [{ host: 'xud1.test.exchangeunion.com', port: 8885 }],
  },
  {
    nodePubKey: '028599d05b18c0c3f8028915a17d603416f7276c822b6b2d20e71a3502bd0f9e0a',
    addresses: [{ host: 'xud2.test.exchangeunion.com', port: 8885 }],
  },
  {
    nodePubKey: '03fd337659e99e628d0487e4f87acf93e353db06f754dccc402f2de1b857a319d0',
    addresses: [{ host: 'xud3.test.exchangeunion.com', port: 8885 }],
  },
] as db.NodeAttributes[];
```

This should change before we change the A records.

@erkarl @sangaman - can you please create a PR?

**Comment by offerm** [comment]
@kilrau I did the change as requested.

You can make the changes to A records even before xud code is fixed. The channel creation script takes care of it (at least on native simnet).

Once the change is done, let me know and I will check that the seed nodes are OK (if not, easy to fix).

**Comment by kilrau** [comment]
> @erkarl @sangaman - can you please create a PR?

Not sure why this didn't happen (I think we can be a bit more pragmatic with these kind of trivial changes), but I just opened this PR.

**Comment by kilrau** [comment]
Tested - working as intended. Kept the old `xud<X>.test.exchangeunion.com` A-Records for now. Will remove once docker is updated.
