### ISSUE TITLE
Smaller Implementation Improvements

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud-simnet#4]
michael1011 @michael1011 14:36
case "$OSTYPE" in
  solaris*) echo "SOLARIS" ;;
  darwin*)  echo "OSX" ;alias tac='tail -r';;
  linux*)   echo "LINUX" ;;
  bsd*)     echo "BSD" ;;
  msys*)    echo "WINDOWS" ;;
  *)        echo "unknown: $OSTYPE" ;;
esac
Is echoing the OSTYPE really needed? Printing a message if the setup is not compatible with the OS of the user (Windows) should be enough?

michael1011 @michael1011 14:44
Also: killall node is pretty reckless. We have a shutdown command in the xucli.
And shouldn't XUD stop first, then the LNDs and afterwards the BTCD/LTCD instances?

michael1011 @michael1011 15:07
alias lndbtc-lncli='lncli --network simnet --no-macaroons --rpcserver=localhost:10002'
alias lndltc-lncli='lncli --network simnet --no-macaroons --rpcserver=localhost:10001'
alias btcctl='btcctl --simnet --rpcuser=xu --rpcpass=xu '
alias ltcctl='ltcctl --simnet --rpcuser=xu --rpcpass=xu --rpcserver=localhost:19556 '
alias lndbtc-lncli='lncli --network simnet --no-macaroons --rpcserver=localhost:10002'
alias lndltc-lncli='lncli --network simnet --no-macaroons --rpcserver=localhost:10001'
The alias for lndbtc-lncli and lndltc-lncli is twice in setup.bash

**Comment by offerm** [comment]
Done!
