### ISSUE TITLE
xud needs an initial xud-simnet-stop and xud-simnet-start to work properly

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud-simnet#5]
Followed guide step by step, but needs to stop and restart simnet environment after first `xud-simnet-start` for everything to work properly

**Comment by offerm** [comment]
I have seen it too.
Looks like an issue with LTCD itself.

Do you suggest we dig into the reason and how to fix it or just change the installation process to include this restart step?
restart can be done automatically by the xud-simnet-channels script.

Let me know what you think.

**Comment by kilrau** [comment]
just include the restart step in the script
