### ISSUE TITLE
Retry open raiden channels

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud-simnet#52]
Status Quo: quite often opening channels fails with

```
xud-test-1: Could send half of 0x46AF55C4320D37bCeA9a3cF6f0Fe18FFf7D9685b to 0x89A1912ECCCA17364De9Afb604431F38D5b9cC08: Payment couldn't be completed (insufficient funds, no route to target or target offline). lock expired
xud-test-1: Could send half of 0x7CB0a7b39358CFac898CD26A6934c2f74d9aAD20 to 0x89A1912ECCCA17364De9Afb604431F38D5b9cC08: Payment couldn't be completed (insufficient funds, no route to target or target offline). lock expired
```

What needs to be done:
1. adjust error message above to ` Could not send`
2. Open issue on raiden side with all possible details (It's definitely not always raiden being offline)
3. Implement retry logic that retries opening a channel once the target raiden client is becoming available again. Best to use raidentransport for that. Opening a channel should be entirely independent from xud.

**Comment by michael1011** [comment]
Should be fixed by https://github.com/ExchangeUnion/xud-tests/pull/7/commits/a7dfac8999eac5c8aa9c4bc22f7919c2c63800db and https://github.com/ExchangeUnion/xud-tests/pull/7/commits/cf941d280bfd3d2ff9912588bab4ad140f558417

@kilrau please try creating a new simnet instance and check whether this issue persist.

**Comment by kilrau** [comment]
Tested on `xud-docker` simnet featuring latest xud master (with resolve request fix): getting no raiden channels at all:

```
  "raiden": {
    "error": "",
    "address": "0x9af4c6D476CEc879c1f6a6A598041079Ce4C2f7A",
    "channels": 0,
    "version": ""
  }
}
simnet > curl -i http://localhost:5002/api/v1/channels
HTTP/1.1 200 OK
mimetype: application/json
Content-Type: application/json
Content-Length: 2
Date: Mon, 26 Aug 2019 15:50:51 GMT

[]simnet > 
```
Raiden is up and running, no log entries regarding channels. Please check on server side, if there's an entry with my address @michael1011

**Comment by kilrau** [comment]
Native simnet works like a charme.

**Comment by michael1011** [comment]
@kilrau your xud-docker setup should have channels: https://discordapp.com/channels/547402601885466658/598158817418805279/615564601882312705

Could your start it up again and check whether there are still not channels?

**Comment by kilrau** [comment]
Just started it, still no channels:

```
  "raiden": {
    "error": "",
    "address": "0x9af4c6D476CEc879c1f6a6A598041079Ce4C2f7A",
    "channels": 0,
    "version": ""
  }
}
simnet > curl -i http://localhost:5002/api/v1/channels
HTTP/1.1 200 OK
mimetype: application/json
Content-Type: application/json
Content-Length: 2
Date: Tue, 27 Aug 2019 08:16:46 GMT

[]simnet > 
```

**Comment by kilrau** [comment]
Can you try running a clean `xud-docker` yourself? Still don't get channels.

**Comment by michael1011** [comment]
This is not a bot issue bot is related to the docker. Closing this in favor of https://github.com/ExchangeUnion/xud-docker/issues/139
