### ISSUE TITLE
geth mining 

### ISSUE THREAD

**Issue by offerm** [ExchangeUnion/xud-simnet#54]
On simnet we have 2 geth instances running (`geth1` and `geth2`) .
The mining script, every 15 seconds, connects to `geth1`, enable mining, disable mining. This way the miner can create a block and stop.

Problems:
1. for some reason the `geth2` is getting into mining mode and is not stopping
2. enable mining, disable mining creates multiple blocks and not just one. 

Impact:

current chain size is bigger than 5M blocks.....

**Comment by kilrau** [comment]
What is geth2 used for? Why not simply bring it down?
