### ISSUE TITLE
Upgrade to go 1.13

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud-simnet#60]
LND 0.8 requires go 1.13 which is why we should upgrade at some point.

But LTCD fails with go 1.13:
```
kilrau@K-Yoga:~$ xud-simnet-install
/usr/bin/python3.7
found all pre-requisites
ltcd repo downloaded
ltcd patched
unable to go instll ltcd
kilrau@K-Yoga:~$ go version
go version go1.13 linux/amd64
```

Doesn't look like https://github.com/ltcsuite/ltcd has any ambitions to be upgraded, so I'd set prio low here and don't spend too much time on it.

My suggestion: stick with go 1.12 for the native simnet setup and we can upgrade to lnd 0.8 with go 1.13 for xud-docker without touching ltcd there.

**Comment by kilrau** [comment]
Dependency: https://github.com/ExchangeUnion/xud-simnet/issues/63 (getting rid of ltcd), then upgrading shouldn't be an issue.

**Comment by kilrau** [comment]
Looks like https://github.com/ltcsuite/ltcd  supports go 1.13 now, so we can update.

**Comment by michael1011** [comment]
Compiling works fine with `go1.13.8`

Closing

**Comment by kilrau** [comment]
Please upgrade simnet to use `go1.13.8` then @michael1011
