### ISSUE TITLE
Open channel bot unreliable

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud-simnet#66]
- LND's need to be restarted (sometimes endless times) to reconnect to our hosted LND's to trigger the channel opening
- raiden channels are opened, but no coins pushed

**Comment by kilrau** [comment]
I don't get channels at all atm.

**Comment by LePremierHomme** [comment]
Channel opening via LND seems to be working fine. 
Closing until someone will experience issues again.
