### ISSUE TITLE
Final: fully automated setup script

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud-simnet#7]
As per https://hackmd.io/s/rye9uA6jX

missing
orders from trading bot
the trading bot was not yet fully deployed to the test servers. Main reason is unclear trading strategy and orders that does not make sense. In addition we should decide if we run it on all servers (may trade between them) or just on one of them. This is also relevant to “trading - understanding what is going on” section below.

working but weak
initial sync with LTCD and BTCD
As part of the installation lndbtc should sync with the remote btcd and lndltc should sync with the remote ltcd.
The sync process, that was suppose to be used on a LAN and not over the internet, can be very long.

mitigation
using neutrino
I managed to setup lnd+neutrino for BTCD. sync time is very short. however:

had to use a special branch of neutrino since the master is not stable and buggy.
LND does not support litecoin+neutrino. Fix is not complicated.
LTCD does not support neutrino. Fix is complicated. Need to cherrypick many BTCD commits into LTCD.
using regtest
we can change the setup and ask each user/exchange to run BTCD and LTCD in regtest mode. block generation will also be at our cloud instances. however:

LND does not support litecoin in regtest mode. easy fix (like the one we did for btcd+litecoin)
setup will become more complicated - need to setup another 2 processes. If we go that route we better have a setup scrip.
setup instructions
improvements to doc/setup
all changes to .bashrc in one take (path, exports, aliases, etc.). Today it is all over the doc.
share rpc.cert between lndbtc and lndltc
add phyton3 as pre-req.
avoid the npm i errors
LND alias - use something to identify the exchange (ip address) and not the same text for all
add a trading example (against the bot) and explain how to check the outcome/status
make sure the user is aware the sync is slowwww and that he should wait until it is over.
setup script
Following the current doc allow the user to understand the environment and the setup. Still, this takes time and open to errors. More over, it we decide to switch from simnet to regtest, we will need to run BTCD and LTCD on each user machine. This will make the setup more complicated.

Alternatively, all this setup can be done with a single setup script.

trading - understanding what is going on
Once everything is setup the user/exchange should experiment with trading by using the CLI.

Once there is a match it is very hard to see the outcome of the match. It is even not clear if there is an error or success.

**Comment by kilrau** [comment]
Actually the more I think about it, I would leave the current guide's steps for illustration purposes and go for docker which automates as much as possible. @offerm

**Comment by offerm** [comment]
@kilrau too late. 
Please run the install again and let me know what you think
updated:
https://hackmd.io/s/HknXXqln7
