### ISSUE TITLE
Missing ensurepip why installing Python3.7 using deadsnakes repository

### ISSUE THREAD

**Issue by reliveyy** [ExchangeUnion/xud-simnet#73]
I got an error when running `xud-simnet-install`

```
ensurepip is missing. Did you install python3.7-dev ?
```

But installing `python3.7-dev` does not solve ensurepip missing problem.

```
$ dpkg-query -L python3.7-dev
/.
/usr
/usr/bin
/usr/share
/usr/share/doc
/usr/share/doc/python3.7
/usr/share/doc/python3.7/HISTORY.gz
/usr/share/doc/python3.7/README.maintainers
/usr/share/doc/python3.7/README.valgrind.gz
/usr/share/doc/python3.7/gdbinit.gz
/usr/share/doc/python3.7/pybench.log
/usr/share/doc/python3.7/test_results
/usr/share/man
/usr/share/man/man1
/usr/bin/python3.7-config
/usr/bin/python3.7m-config
/usr/share/doc/python3.7-dev
/usr/share/man/man1/python3.7-config.1.gz
/usr/share/man/man1/python3.7m-config.1.gz
```

And the package `python3.7-dev` does not contain module `ensurepip`. I'm afraid the only way to have this `ensurepip` module installed is to compile Python3.7 from the source.

Related to https://github.com/deadsnakes/issues/issues/79

References:
1. [ensurepip is disabled in Debian/Ubuntu for the system python](https://askubuntu.com/questions/879437/ensurepip-is-disabled-in-debian-ubuntu-for-the-system-python)

**Comment by reliveyy** [comment]
Installing Python3.7 from the source solved my issue.

**Comment by reliveyy** [comment]
A better solution is installing `python3.7-venv` instead.

**Comment by kilrau** [comment]
due to raiden removal not relevant anymore
