### ISSUE TITLE
Fixes

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud-simnet#76]
- reset btcd/ltcd chain
- rewrite open channel bot, take out raiden from setup
- take out raiden from local setup, geth+raiden from xud1.simnet cloud setup
- test with xud-docker simnet setup

**Comment by michael1011** [comment]
Actually the raiden changes never made it into the master branch of the channel bot https://github.com/ExchangeUnion/xud-tests/pull/7. But I still think a lot could be improved in the existing codebase of the bot

**Comment by kilrau** [comment]
We are more or less done with this.
